id: I68E9A5D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:05:42+00:00'
last_modified: '2022-06-10T09:57:49.401017+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29653
  title: ལས་བརྒྱ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    314D:
      image_group_id: I1KG20827
      title: Volume 1 of las brgya tham pa
      total_pages: 806
      order: 1
      base_file: 314D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
